"""A deliberately broken input folder must produce warnings, not silence.

The failure mode being designed out is a complete, professional-looking report
built on data the model quietly patched over. These tests assert that every such
fallback is announced.

The Synthetic_Broken fixture is generated by tools/make_synthetic_zone.py and
contains KNOWN defects: no population attribute at all, an isolated network
fragment that reaches no safe zone, and a 0.2 m link. Testing against it, rather
than against the real Chimbote data, means these tests keep their meaning even
if the real data is ever cleaned up.
"""

from __future__ import annotations

import pytest

pytestmark = pytest.mark.engine


def warnings_of(run):
    # pyNetLogo raises on an empty NetLogo list, so check the length first.
    if int(run.number("length input-warnings")) == 0:
        return []
    return [str(w) for w in run.report("input-warnings")]


def test_the_shipped_zone_reports_its_known_problems(engine):
    run = engine().populate()
    messages = " | ".join(warnings_of(run))
    assert "DISCONNECTED NETWORK" in messages, (
        "884 of 4468 nodes reach no safe zone and nothing said so")
    assert "POPULATION ATTRIBUTE" in messages
    assert "DEGENERATE LINKS" in messages


def test_disconnected_network_warning_states_the_scale(engine):
    run = engine().populate()
    disconnected = [w for w in warnings_of(run) if "DISCONNECTED" in w]
    assert disconnected
    assert "884" in disconnected[0] and "19.8" in disconnected[0], (
        "the warning must quantify the problem, not merely mention it")


def test_population_mismatch_is_reported(engine):
    """Asking for far fewer people than the census holds must be flagged."""
    run = engine(adults=10, elderly=1, children=1).populate()
    assert any("POPULATION MISMATCH" in w for w in warnings_of(run))


def test_snap_distance_warning_appears_when_the_limit_is_tightened(engine):
    strict = engine(**{"max-snap-distance": 1}).populate()
    assert any("ENTRY DISTANCE" in w for w in warnings_of(strict)), (
        "agents placed far from the network must be reported")


def test_warnings_are_not_duplicated(engine):
    run = engine().populate()
    messages = warnings_of(run)
    assert len(messages) == len(set(messages))


# --- against the deliberately broken fixture --------------------------------

def test_missing_population_attribute_is_announced(engine):
    """Synthetic_Broken has no T_TOTAL, Population or POP column at all."""
    run = engine(zone="Synthetic_Broken", adults=30, elderly=0, children=0,
                 **{"tsunami-eta": 20}).populate()
    messages = warnings_of(run)
    population = [w for w in messages if "POPULATION ATTRIBUTE" in w]
    assert population, "a block layer with no population column said nothing"
    assert any("UNIFORMLY" in w for w in population), (
        "the warning must say that population is being spread uniformly")
    assert any("not trustworthy" in w for w in population), (
        "the warning must state the consequence, not just the fact")


def test_isolated_fragment_is_announced(engine):
    run = engine(zone="Synthetic_Broken", adults=30, elderly=0, children=0,
                 **{"tsunami-eta": 20}).populate()
    assert any("DISCONNECTED NETWORK" in w for w in warnings_of(run))


def test_sub_metre_link_is_announced(engine):
    """The fixture contains exactly one 0.2 m link."""
    run = engine(zone="Synthetic_Broken", adults=30, elderly=0, children=0,
                 **{"tsunami-eta": 20}).populate()
    degenerate = [w for w in warnings_of(run) if "DEGENERATE LINKS" in w]
    assert degenerate, "a 0.2 m link produced no warning"
    assert "1 links" in degenerate[0] or "1 link" in degenerate[0]


def test_a_clean_zone_reports_no_warnings(engine):
    """Silence must be informative: a good folder must produce NO warnings.

    Without this, the warning tests could pass simply because the model always
    complains about something.
    """
    # 200 agents against a census total of 200: no mismatch to report.
    run = engine(zone="Synthetic_Corridor", adults=200, elderly=0, children=0,
                 **{"tsunami-eta": 30, "departure-mean": 0}).populate()
    assert warnings_of(run) == [], (
        f"a clean synthetic zone raised warnings: {warnings_of(run)}")


def test_a_zone_with_no_safe_zone_is_refused(engine):
    """Nobody can evacuate, so the model must REFUSE at setup.

    Reporting "100% stranded" would be a plausible-looking output folder built
    on a data error, which is precisely the failure mode being designed out.
    """
    import pynetlogo
    with pytest.raises(pynetlogo.NetLogoException, match="[Nn]o safe zones"):
        engine(zone="Synthetic_NoSafeZone", adults=10, elderly=0,
               children=0, **{"tsunami-eta": 20})
